<?php

use Illuminate\Database\Seeder;

class them_ve_cuoc extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('user_bets')->insert([
        	'match_id'=>5,
        	'user_id'=>2,
        	'coin'=>350,
        	'outcome'=>'1',
        	'state'=>false
        ]);
        DB::table('user_bets')->insert([
        	'match_id'=>2,
        	'user_id'=>2,
        	'coin'=>500,
        	'outcome'=>'x',
        	'state'=>true
        ]);
        DB::table('user_bets')->insert([
        	'match_id'=>3,
        	'user_id'=>3,
        	'coin'=>300,
        	'outcome'=>'2',
        	'state'=>true
        ]);
        DB::table('user_bets')->insert([
        	'match_id'=>4,
        	'user_id'=>4,
        	'coin'=>500,
        	'outcome'=>'1',
        	'state'=>true
        ]);
        DB::table('user_bets')->insert([
        	'match_id'=>5,
        	'user_id'=>3,
        	'coin'=>300,
        	'outcome'=>'2',
        	'state'=>true
        ]);
        DB::table('user_bets')->insert([
        	'match_id'=>6,
        	'user_id'=>2,
        	'coin'=>2000,
        	'outcome'=>'1',
        	'state'=>true
        ]);
        DB::table('user_bets')->insert([
        	'match_id'=>2,
        	'user_id'=>4,
        	'coin'=>300,
        	'outcome'=>'x',
        	'state'=>true
        ]);
        DB::table('user_bets')->insert([
        	'match_id'=>2,
        	'user_id'=>3,
        	'coin'=>1000,
        	'outcome'=>'1',
        	'state'=>true
        ]);
        DB::table('user_bets')->insert([
        	'match_id'=>3,
        	'user_id'=>2,
        	'coin'=>300,
        	'outcome'=>'2',
        	'state'=>true
        ]);
        DB::table('user_bets')->insert([
        	'match_id'=>4,
        	'user_id'=>4,
        	'coin'=>500,
        	'outcome'=>'1',
        	'state'=>true
        ]);
        DB::table('user_bets')->insert([
        	'match_id'=>5,
        	'user_id'=>3,
        	'coin'=>300,
        	'outcome'=>'x',
        	'state'=>true
        ]);
        DB::table('user_bets')->insert([
        	'match_id'=>6,
        	'user_id'=>4,
        	'coin'=>300,
        	'outcome'=>'1',
        	'state'=>true
        ]);
        DB::table('user_bets')->insert([
        	'match_id'=>1,
        	'user_id'=>2,
        	'coin'=>200,
        	'outcome'=>'1',
        	'state'=>true
        ]);
        DB::table('user_bets')->insert([
        	'match_id'=>4,
        	'user_id'=>2,
        	'coin'=>700,
        	'outcome'=>'x',
        	'state'=>true
        ]);
        DB::table('user_bets')->insert([
        	'match_id'=>3,
        	'user_id'=>4,
        	'coin'=>600,
        	'outcome'=>'2',
        	'state'=>true
        ]);

    }
}
